#=======================================================================
# Makefile for riscv-tests/isa
#-----------------------------------------------------------------------

XLEN ?= 64

src_dir := ./riscv-tests/isa
out_dir := ./tests
env_dir := ./env

include $(src_dir)/rv32ui/Makefrag
include $(src_dir)/rv32um/Makefrag

default: all

#--------------------------------------------------------------------
# Build rules
#--------------------------------------------------------------------

RISCV_PREFIX ?= riscv$(XLEN)-unknown-elf-
RISCV_GCC ?= $(RISCV_PREFIX)gcc
RISCV_GCC_OPTS ?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles
RISCV_OBJDUMP ?= $(RISCV_PREFIX)objdump

vpath %.S $(src_dir)

#------------------------------------------------------------
# Build assembly tests

%.dump: %
	$(RISCV_OBJDUMP) -D $< > $@

define compile_template

$$($(1)_p_tests): $(1)-p-%: $(src_dir)/$(1)/%.S
	$$(RISCV_GCC) $(2) $$(RISCV_GCC_OPTS) -I$(env_dir) -I$(src_dir)/macros/scalar -T$(env_dir)/link.ld  $$< -o $(out_dir)/$$@

$(1)_tests += $$($(1)_p_tests)
$(1)_tests_dump = $$(addsuffix .dump, $$($(1)_tests))
tests += $$($(1)_tests)

.PHONY: $(1)


endef

$(eval $(call compile_template,rv32ui,-march=rv32g -mabi=ilp32))
$(eval $(call compile_template,rv32um,-march=rv32g -mabi=ilp32))

tests_dump = $(addsuffix .dump, $(tests))
tests_hex = $(addsuffix .hex, $(tests))

junk += $(addprefix $(out_dir)/, $(tests) $(tests_dump) $(tests_hex))

#------------------------------------------------------------
# Default

rv32ui: $(rv32ui_tests)
rv32um: $(rv32um_tests)

all: $(tests)

dump: $(addprefix $(out_dir)/, $(tests_dump))

#------------------------------------------------------------
# Clean up

clean:
	rm -rf $(junk)
