// This file is automatically generated by cargo openvm. Do not rename or edit.
openvm_algebra_guest::moduli_macros::moduli_init! { "115792089237316195423570985008687907853269984665640564039457584007908834671663" }
openvm_algebra_guest::complex_macros::complex_init! { Complex { mod_idx = 0 } }
