// This file is automatically generated by cargo openvm. Do not rename or edit.
openvm_algebra_guest::moduli_macros::moduli_init! { "998244353", "1000000007", "1000000009", "987898789" }
openvm_algebra_guest::complex_macros::complex_init! { Complex2 { mod_idx = 2 } }
