// This file is automatically generated by cargo openvm. Do not rename or edit.
openvm_algebra_guest::moduli_macros::moduli_init! { "52435875175126190479447740508185965837690552500527637822603658699938581184513" }
