name: Bigint Extension Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
      - "extensions/bigint/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  OPENVM_FAST_TEST: "1"

jobs:
  tests:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=64cpu-linux-arm64

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest

      - name: Run bigint extension crate tests
        working-directory: extensions/bigint/circuit
        run: |
          cargo nextest run --cargo-profile=fast

      - name: Run bigint integration tests
        working-directory: extensions/bigint/tests
        run: |
          rustup component add rust-src --toolchain nightly-2024-10-30
          cargo nextest run --cargo-profile=fast
