name: RISC-V Test Vectors

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
      - "crates/vm/**"
      - "crates/toolchain/**"
      - "Cargo.toml"
      - ".github/workflows/riscv.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  OPENVM_FAST_TEST: "1"

jobs:
  tests:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=64cpu-linux-arm64
      - image=arm64-rust-riscv-dev-32gb # for riscv-gnu-toolchain
      - extras=s3-cache

    steps:
      - uses: runs-on/action@v1
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-02-14
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Makefile
        working-directory: crates/toolchain/tests/rv32im-test-vectors
        run: |
          export PATH=/opt/riscv/bin:$PATH
          make

      - name: Run RISC-V test vector tests
        working-directory: crates/toolchain/tests
        run: |
          rustup component add rust-src --toolchain nightly-2025-02-14
          cargo nextest run --cargo-profile=fast --run-ignored only -- test_rv32im_riscv_vector_runtime
